% ASLtranslate II 

% Author: Andrea Murphy
% Date: Spring 2020
% DESC: Training the Network 

% set training parameters
options = trainingOptions('sgdm', ...
    'MiniBatchSize',10, ...
    'MaxEpochs',6, ...
    'InitialLearnRate',1e-4, ...
    'Shuffle','every-epoch', ...
    'ValidationData',augValidation, ...
    'ValidationFrequency',3, ...
    'Verbose',false, ...
    'Plots','training-progress'); 

% Perform training
netTransfer = trainNetwork(augTrain,layers,options);
